---
stages:
  - lint

todo-reminder:
  stage: lint
  image: leo108/todo-reminder:latest
  script:
    - |
      if todo-reminder todo-reminder.toml; then
        echo "No TODO issues found."
      else
        echo "TODO issues were found. Check the output above."
        exit 1
      fi
  artifacts:
    when: always
    paths:
      - todo-report.json
    expire_in: 1 week
