---
stages:
  - lint

todo-reminder:
  stage: lint
  image: leo108/todo-reminder:latest
  script:
    - |
      if todo-reminder todo-reminder.toml --no-tty; then
        echo "No TODO issues found."
      else
        echo "TODO issues were found. Check the output above."
        exit 1
      fi

todo-reminder-due-soon:
  stage: lint
  image: leo108/todo-reminder:latest
  needs:
    - todo-reminder
  script:
    - |
      if [ -z "${CI_MERGE_REQUEST_IID}" ]; then
        echo "Not in a merge request context. Skipping TODOs due soon check."
        exit 0
      fi
      
      todo-reminder todo-reminder.toml --due-in=30 --check-due-only --exit-zero --format=table --no-tty > todos-due-soon-report.txt
      
      if [ -s todos-due-soon-report.txt ]; then
        echo "TODOs due within 30 days were found."
        
        apk add curl
        
        TABLE_CONTENT=$(cat todos-due-soon-report.txt)
        COMMENT="### ⚠️ TODOs Due Within 30 Days\n\nThe following TODOs are due soon and should be addressed:\n\n\`\`\`\n${TABLE_CONTENT}\n\`\`\`"
        
        curl --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
          --header "Content-Type: application/json" \
          --data "{\"body\":\"${COMMENT}\"}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes"
      else
        echo "No TODOs due within 30 days found."
      fi
  artifacts:
    when: always
    paths:
      - todos-due-soon-report.txt
    expire_in: 1 week
  only:
    - merge_requests
