name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test-job.yml

  binary:
    needs: test
    uses: ./.github/workflows/binary-job.yml

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-reminder:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-reminder:${{ steps.get_version.outputs.VERSION }}

  create-release:
    needs: binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Move artifacts to release folder
        run: |
          mkdir release
          for f in artifacts/*/*; do
            mv $f release/$(basename $(dirname $f));
          done
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**/*
          generate_release_notes: true
          draft: false
          prerelease: false 